### ISSUE TITLE
Brainstorm!

### ISSUE THREAD

**Issue by gmemstr** [tomhodgins/css-package-manager#1]
Let's brainstorm how we could make this work!

Taken from Discord:

![image](https://user-images.githubusercontent.com/1878840/68939959-da2d1600-0799-11ea-9af2-cf07f2163a96.png)

**Comment by gmemstr** [comment]
I personally quite like the idea of embedding the packages directly into the stylesheet, although I wonder how easy the second, "alternative" approach would be. Maybe we take a hybrid approach? e.g

```css
@--package-bootstrap {}
body {
	display: bootstrap-display;
}
```

Feel free to correct my CSS formatting but that's sort of what I have in my head. `@--package-` would help us parse out the packages that need to be brought in, maybe with the ability to define explicit URLs/versions/hashes with

```css
@--package-bootstrap {
	url: url("https://example.com/bootstrap/v1.css");
}
```

(again, CSS syntax isn't perfect)
